config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/about-us' => 'static#about_us'
  get '/portfolio' => 'static#portfolio'
  get '/team' => 'static#team'
  get '/thankyou' => 'static#thankyou', as: 'thankyou'
  get '/contact-us' => 'contacts#new', as: 'new_contact'
  post '/contact-us' => 'contacts#create', as: 'contact_us'
  
  get '/contact_us', to: redirect('/contact-us')

  root to: 'static#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact
  include ActiveAttr::Model

  attr_accessor :name, :email, :website, :company, :phone, :message

  validates :name, :email, :phone, :message, presence: true
  validates :email, format: { with: Devise.email_regexp }

  def notify
    Notifier.notify_contact(self).deliver_now!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @title = 'Contact Us | Bhagwant Export'
    @contact = Contact.new
  end

  def create
    @title = 'Contact Us | Bhagwant Export'
    @contact = Contact.new params[:contact]
    #@contact.message = @contact.message[0..290]
    contact_valid = @contact.valid? ? true : false
    if contact_valid
      @contact.notify
      redirect_to thankyou_path and return
      #send_mail and display thankyou page
    else
      render 'new'
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  # caches_page :portfolio, :team, :testimonials

  def portfolio
    @products = PRODUCTS.select { |p| p[:display] }
    @keywords = "fruits vegetables grains"
    @description = "Leading exportes of fruits vegetables and grains"
    @title = 'Bhagwant Export | Our Products'
  end

  def team
  end

  def home
    @products = PRODUCTS.select { |p| p[:display] }
    @title = "Leading exporters of fresh fruits and vegetables | Bhagwant Export"
    @keywords = "Bhagwant Export"
  end

  def ping
    render :text => 'Hello'
  end

  def contact_us
    @title = 'Bhagwant Export | Contact Us'
    @keywords = "Bhagwant Export"
    @description = "Contact Us at Bhagwant export for fresh organic farm grown products"
  end

  def about_us
    @title = 'Fruits and vegetables exporters | About Us'
    @keywords = "Bhagwant export | fresh fruits vegetables exporters in indina"
  end

  def thankyou
    @title = 'Thank you | Bhagwant Export'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def any_errors(contact, field)
    "errors" if contact.errors.keys.include? field.to_sym
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_helper.rb
module StaticHelper
  def check_if_active(tab)
    request.path == tab ? 'active' : ''
  end
end

app/views/contacts/new.html.haml
= render 'shared/breadcrumbs', data: nil
.container
  .row.flow-offset-1
    .col-md-4.text-center.text-md-left
      %address.contact-block.inset-sm-min-2.text-left
        %dl
          %dt.h4 Bhagwant Export
          %dt.h6 ADDRESS
          %dd
            Maharashtra, India.
          %dt.h6 WE ARE OPEN
          %dd Open hours: 8.00 AM - 20.00 PM (IST)
          %dt.h6 PHONE
          %dd
            %a{:href => "callto:#"} +91-9403867440  
          %dt.h6 E-MAIL
          %dd
            %a{:href => "mailto:bhagwantexports@gmail.com"} bhagwantexports@gmail.com
          %dt.h6 FOUNDER
          %dd
            Mr. Mayur M Jadhav
        %ul.list-inline.list-inline-3
          %li
            %a.material-design-facebook56{:href => "#"}
          %li
            %a.material-design-google119{:href => "#"}
          %li
            %a.material-design-twitter47{:href => "#"}
    .col-md-8.well-sm.btn-shadow.inset-sm-min.bg-white.round-large
      %h4 Send an Enquiry
      .contact-form
        = form_for @contact, url: contact_us_path, method: :post do |f|
          .row
            .form-group.col-sm-6
              %label{:for => "name"} Name
              = f.text_field :name, class: "form-control #{any_errors(@contact, 'name')}", id: 'name', placeholder: 'Enter your name'
            .form-group.col-sm-6
              %label{:for => "email"} Email
              = f.text_field :email, class: "form-control #{any_errors(@contact, 'email')}", id: 'email', placeholder: 'Enter your email address'
          .row
            .form-group.col-sm-6
              %label{:for => "website"} Website
              = f.text_field :website, class: "form-control #{any_errors(@contact, 'website')}", id: 'name', placeholder: 'Enter your website'
            .form-group.col-sm-6
              %label{:for => "company"} Company Name
              = f.text_field :company, class: "form-control #{any_errors(@contact, 'company')}", id: 'email', placeholder: 'Enter your company name'
          .row
            .form-group.col-sm-6
              %label{:for => "phone"} Phone
              = f.text_field :phone, class: "form-control #{any_errors(@contact, 'phone')}", id: 'phone', placeholder: 'Enter your phone number'
          .row
            .form-group.col-sm-12
              %label{:for => "phone"} Message
              = f.text_area :message, class: "form-control #{any_errors(@contact, 'message')}", rows: '7'
            / .form-group
            /   = recaptcha_tags :display => {:theme => 'white'}
            /   - if @contact.errors[:recaptcha]
            /     %span.has-error
            /       %label.control-label= @contact.errors[:recaptcha].join(' ')
          .row
            .form-group.col-sm-6
              = f.submit 'Submit', class: 'btn btn-primary round-xl center'

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title #{@title}
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %meta{:name => "keywords", :content => "#{@keywords || 'Bhagwant Export'}"}
    %meta{:name => "description", :content => "#{@description || 'Bhagwant Export'}"}

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .page
      = render 'shared/header'
      = yield
      = render 'shared/footer'

app/views/notifier/notify_contact.html.haml
%p
  Hello,
%p
  You have received an enquiry from Bhagwant Export site. 
  Details are:
%p 
  Name: #{@contact.name}
  %br  
  Email: #{@contact.email}
  %br
  Phone: #{@contact.phone}
  %br
  Company: #{@contact.company}
  Message: #{@contact.message}
%p
  Thank You.

app/views/shared/_breadcrumbs.html.haml
.breadcrumbs
  .container
    .row
      .col-lg-4.col-sm-4
        %h1 #{data}
      .col-lg-8.col-sm-8
        - if data
          %ol.breadcrumb.pull-right
            %li
              %a{:href => "#"} Home
            %li
              %a{:href => "#"} Pages
            %li.active #{data}

app/views/shared/_footer.html.haml
%footer.footer
  .container
    .row
      / .container
      /   %h1 stay connected
      /   %ul.social-link-footer.list-unstyled
      /     %li
      /       %a{:href => "https://www.facebook.com/bhagwantexports/", target: "_blank", alt: 'Facebook', class: 'social-rounded-icon'}
      /         %i.icon-facebook
      /     %li
      /       %a{:href => "https://www.linkedin.com/company/bhagwant-export", target: "_blank", alt: 'Linked In', class: 'social-rounded-icon'}
      /         %i.icon-linkedin
      /     %li
      /       %a{:href => "#", target: "_blank", alt: 'Instagram', class: 'social-rounded-icon'}
      /         %i.icon-instagram

    %br
    .row
      .text-center.footer_nav_links
        = link_to 'Home', root_path
        |
        = link_to 'Our Products', 'portfolio'
        |
        = link_to 'Contact Us', 'contact-us'
        |
        = link_to 'About Us', 'about-us'
        |
        = link_to 'Facebook', "https://www.facebook.com/bhagwantexports/", target: "_blank"
        |
        = link_to 'LinkedIn', "https://www.linkedin.com/company/bhagwant-export", target: "_blank"
    .row
      .copyright.text-center
        Copyright © Bhagwant Export

app/views/shared/_header.html.haml
%header.header-frontend
  .navbar.navbar-default.navbar-static-top
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .row{:style => "margin-top: 0px;"}
          %a.navbar-brand.pull-left{:href => root_path}
            = image_tag 'bhagwant-exports-logo.jpg', alt: 'Bhagwant Export', style: "width: 180px;"
      .navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li{class: "#{check_if_active('/')}"}
            = link_to 'Home', root_path

          %li{class: "#{check_if_active('/portfolio')}"}
            = link_to 'Our Products', portfolio_path

          %li{class: "#{check_if_active('/contact-us')}"}
            = link_to 'Contact Us', new_contact_path

          %li{class: "#{check_if_active('/about-us')}"}
            = link_to 'About Us', about_us_path